// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: market/v1/market.proto

package marketv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BuySell represents the aggressor side of a trade.
type BuySell int32

const (
	BuySell_BUY_SELL_UNSPECIFIED BuySell = 0
	BuySell_BUY_SELL_BUY         BuySell = 1
	BuySell_BUY_SELL_SELL        BuySell = 2
)

// Enum value maps for BuySell.
var (
	BuySell_name = map[int32]string{
		0: "BUY_SELL_UNSPECIFIED",
		1: "BUY_SELL_BUY",
		2: "BUY_SELL_SELL",
	}
	BuySell_value = map[string]int32{
		"BUY_SELL_UNSPECIFIED": 0,
		"BUY_SELL_BUY":         1,
		"BUY_SELL_SELL":        2,
	}
)

func (x BuySell) Enum() *BuySell {
	p := new(BuySell)
	*p = x
	return p
}

func (x BuySell) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuySell) Descriptor() protoreflect.EnumDescriptor {
	return file_market_v1_market_proto_enumTypes[0].Descriptor()
}

func (BuySell) Type() protoreflect.EnumType {
	return &file_market_v1_market_proto_enumTypes[0]
}

func (x BuySell) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuySell.Descriptor instead.
func (BuySell) EnumDescriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{0}
}

// Trade represents a single executed trade on an exchange.
//
// Prices and quantities are serialised as strings to preserve full decimal
// precision (avoid IEEE-754 rounding). Downstream consumers (ClickHouse)
// parse them into Decimal128 / Float64 as appropriate.
type Trade struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique, time-ordered identifier for this event (UUID v7).
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Exchange-assigned trade identifier (may be empty on some venues).
	ExchangeTradeId string `protobuf:"bytes,2,opt,name=exchange_trade_id,json=exchangeTradeId,proto3" json:"exchange_trade_id,omitempty"`
	// Originating exchange (e.g. "binance", "kraken").
	Exchange string `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Trading pair in canonical form, e.g. "BTC/USDT".
	Pair string `protobuf:"bytes,4,opt,name=pair,proto3" json:"pair,omitempty"`
	// Execution price (decimal string, e.g. "67432.15").
	Price string `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	// Executed quantity (decimal string, e.g. "0.00423").
	Quantity string `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Aggressor side.
	Side BuySell `protobuf:"varint,7,opt,name=side,proto3,enum=market.v1.BuySell" json:"side,omitempty"`
	// Exchange-reported trade timestamp in Unix microseconds.
	// Microsecond precision maps directly to ClickHouse DateTime64(6).
	TimestampUs   int64 `protobuf:"varint,8,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_market_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *Trade) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Trade) GetExchangeTradeId() string {
	if x != nil {
		return x.ExchangeTradeId
	}
	return ""
}

func (x *Trade) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Trade) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Trade) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Trade) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Trade) GetSide() BuySell {
	if x != nil {
		return x.Side
	}
	return BuySell_BUY_SELL_UNSPECIFIED
}

func (x *Trade) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

// PriceLevel represents a single row in an order book (price + quantity).
type PriceLevel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Price of this level (decimal string).
	Price string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	// Quantity available at this level.
	// A value of "0" signals removal of the level.
	Quantity      string `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_market_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *PriceLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevel) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

// OrderBookUpdate carries an incremental delta for one side of the order book.
// Consumers apply these deltas sequentially to maintain a local order book.
type OrderBookUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique, time-ordered identifier for this event (UUID v7).
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Originating exchange.
	Exchange string `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Trading pair in canonical form.
	Pair string `protobuf:"bytes,3,opt,name=pair,proto3" json:"pair,omitempty"`
	// Exchange-assigned sequence number for ordering deltas.
	// Zero if the exchange does not provide one.
	Sequence int64 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Updated bid levels (buy side).
	Bids []*PriceLevel `protobuf:"bytes,5,rep,name=bids,proto3" json:"bids,omitempty"`
	// Updated ask levels (sell side).
	Asks []*PriceLevel `protobuf:"bytes,6,rep,name=asks,proto3" json:"asks,omitempty"`
	// Exchange-reported update timestamp in Unix microseconds.
	TimestampUs   int64 `protobuf:"varint,7,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookUpdate) Reset() {
	*x = OrderBookUpdate{}
	mi := &file_market_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookUpdate) ProtoMessage() {}

func (x *OrderBookUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookUpdate.ProtoReflect.Descriptor instead.
func (*OrderBookUpdate) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *OrderBookUpdate) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OrderBookUpdate) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OrderBookUpdate) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *OrderBookUpdate) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OrderBookUpdate) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderBookUpdate) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *OrderBookUpdate) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

// Ticker carries the 24-hour rolling statistics for a trading pair.
type Ticker struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique, time-ordered identifier for this event (UUID v7).
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Originating exchange.
	Exchange string `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	// Trading pair in canonical form.
	Pair string `protobuf:"bytes,3,opt,name=pair,proto3" json:"pair,omitempty"`
	// Opening price of the 24 h window (decimal string).
	Open string `protobuf:"bytes,4,opt,name=open,proto3" json:"open,omitempty"`
	// Highest price in the 24 h window (decimal string).
	High string `protobuf:"bytes,5,opt,name=high,proto3" json:"high,omitempty"`
	// Lowest price in the 24 h window (decimal string).
	Low string `protobuf:"bytes,6,opt,name=low,proto3" json:"low,omitempty"`
	// Last traded price (decimal string).
	Close string `protobuf:"bytes,7,opt,name=close,proto3" json:"close,omitempty"`
	// Base-asset volume traded in the 24 h window (decimal string).
	Volume string `protobuf:"bytes,8,opt,name=volume,proto3" json:"volume,omitempty"`
	// Quote-asset volume traded in the 24 h window (decimal string).
	QuoteVolume string `protobuf:"bytes,9,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"`
	// Snapshot timestamp in Unix microseconds.
	TimestampUs   int64 `protobuf:"varint,10,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticker) Reset() {
	*x = Ticker{}
	mi := &file_market_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker) ProtoMessage() {}

func (x *Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker.ProtoReflect.Descriptor instead.
func (*Ticker) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *Ticker) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Ticker) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Ticker) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Ticker) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Ticker) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Ticker) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Ticker) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *Ticker) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Ticker) GetQuoteVolume() string {
	if x != nil {
		return x.QuoteVolume
	}
	return ""
}

func (x *Ticker) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

// MarketEvent is the top-level message published to the "market.events" topic.
// Each record is exactly one of the concrete market-data types, wrapped here
// so that a single topic + schema can carry the full stream.
type MarketEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MarketEvent_Trade
	//	*MarketEvent_OrderBookUpdate
	//	*MarketEvent_Ticker
	Payload       isMarketEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketEvent) Reset() {
	*x = MarketEvent{}
	mi := &file_market_v1_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketEvent) ProtoMessage() {}

func (x *MarketEvent) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketEvent.ProtoReflect.Descriptor instead.
func (*MarketEvent) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{4}
}

func (x *MarketEvent) GetPayload() isMarketEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MarketEvent) GetTrade() *Trade {
	if x != nil {
		if x, ok := x.Payload.(*MarketEvent_Trade); ok {
			return x.Trade
		}
	}
	return nil
}

func (x *MarketEvent) GetOrderBookUpdate() *OrderBookUpdate {
	if x != nil {
		if x, ok := x.Payload.(*MarketEvent_OrderBookUpdate); ok {
			return x.OrderBookUpdate
		}
	}
	return nil
}

func (x *MarketEvent) GetTicker() *Ticker {
	if x != nil {
		if x, ok := x.Payload.(*MarketEvent_Ticker); ok {
			return x.Ticker
		}
	}
	return nil
}

type isMarketEvent_Payload interface {
	isMarketEvent_Payload()
}

type MarketEvent_Trade struct {
	Trade *Trade `protobuf:"bytes,1,opt,name=trade,proto3,oneof"`
}

type MarketEvent_OrderBookUpdate struct {
	OrderBookUpdate *OrderBookUpdate `protobuf:"bytes,2,opt,name=order_book_update,json=orderBookUpdate,proto3,oneof"`
}

type MarketEvent_Ticker struct {
	Ticker *Ticker `protobuf:"bytes,3,opt,name=ticker,proto3,oneof"`
}

func (*MarketEvent_Trade) isMarketEvent_Payload() {}

func (*MarketEvent_OrderBookUpdate) isMarketEvent_Payload() {}

func (*MarketEvent_Ticker) isMarketEvent_Payload() {}

var File_market_v1_market_proto protoreflect.FileDescriptor

const file_market_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x16market/v1/market.proto\x12\tmarket.v1\"\xfb\x01\n" +
	"\x05Trade\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12*\n" +
	"\x11exchange_trade_id\x18\x02 \x01(\tR\x0fexchangeTradeId\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x12\n" +
	"\x04pair\x18\x04 \x01(\tR\x04pair\x12\x14\n" +
	"\x05price\x18\x05 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\tR\bquantity\x12&\n" +
	"\x04side\x18\a \x01(\x0e2\x12.market.v1.BuySellR\x04side\x12!\n" +
	"\ftimestamp_us\x18\b \x01(\x03R\vtimestampUs\">\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\"\xf1\x01\n" +
	"\x0fOrderBookUpdate\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x12\n" +
	"\x04pair\x18\x03 \x01(\tR\x04pair\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x03R\bsequence\x12)\n" +
	"\x04bids\x18\x05 \x03(\v2\x15.market.v1.PriceLevelR\x04bids\x12)\n" +
	"\x04asks\x18\x06 \x03(\v2\x15.market.v1.PriceLevelR\x04asks\x12!\n" +
	"\ftimestamp_us\x18\a \x01(\x03R\vtimestampUs\"\x81\x02\n" +
	"\x06Ticker\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12\x12\n" +
	"\x04pair\x18\x03 \x01(\tR\x04pair\x12\x12\n" +
	"\x04open\x18\x04 \x01(\tR\x04open\x12\x12\n" +
	"\x04high\x18\x05 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\tR\x03low\x12\x14\n" +
	"\x05close\x18\a \x01(\tR\x05close\x12\x16\n" +
	"\x06volume\x18\b \x01(\tR\x06volume\x12!\n" +
	"\fquote_volume\x18\t \x01(\tR\vquoteVolume\x12!\n" +
	"\ftimestamp_us\x18\n" +
	" \x01(\x03R\vtimestampUs\"\xb9\x01\n" +
	"\vMarketEvent\x12(\n" +
	"\x05trade\x18\x01 \x01(\v2\x10.market.v1.TradeH\x00R\x05trade\x12H\n" +
	"\x11order_book_update\x18\x02 \x01(\v2\x1a.market.v1.OrderBookUpdateH\x00R\x0forderBookUpdate\x12+\n" +
	"\x06ticker\x18\x03 \x01(\v2\x11.market.v1.TickerH\x00R\x06tickerB\t\n" +
	"\apayload*H\n" +
	"\aBuySell\x12\x18\n" +
	"\x14BUY_SELL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fBUY_SELL_BUY\x10\x01\x12\x11\n" +
	"\rBUY_SELL_SELL\x10\x02BNZLgithub.com/0himera/cryptalize/collector-go/internal/proto/market/v1;marketv1b\x06proto3"

var (
	file_market_v1_market_proto_rawDescOnce sync.Once
	file_market_v1_market_proto_rawDescData []byte
)

func file_market_v1_market_proto_rawDescGZIP() []byte {
	file_market_v1_market_proto_rawDescOnce.Do(func() {
		file_market_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_v1_market_proto_rawDesc), len(file_market_v1_market_proto_rawDesc)))
	})
	return file_market_v1_market_proto_rawDescData
}

var file_market_v1_market_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_market_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_market_v1_market_proto_goTypes = []any{
	(BuySell)(0),            // 0: market.v1.BuySell
	(*Trade)(nil),           // 1: market.v1.Trade
	(*PriceLevel)(nil),      // 2: market.v1.PriceLevel
	(*OrderBookUpdate)(nil), // 3: market.v1.OrderBookUpdate
	(*Ticker)(nil),          // 4: market.v1.Ticker
	(*MarketEvent)(nil),     // 5: market.v1.MarketEvent
}
var file_market_v1_market_proto_depIdxs = []int32{
	0, // 0: market.v1.Trade.side:type_name -> market.v1.BuySell
	2, // 1: market.v1.OrderBookUpdate.bids:type_name -> market.v1.PriceLevel
	2, // 2: market.v1.OrderBookUpdate.asks:type_name -> market.v1.PriceLevel
	1, // 3: market.v1.MarketEvent.trade:type_name -> market.v1.Trade
	3, // 4: market.v1.MarketEvent.order_book_update:type_name -> market.v1.OrderBookUpdate
	4, // 5: market.v1.MarketEvent.ticker:type_name -> market.v1.Ticker
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_market_v1_market_proto_init() }
func file_market_v1_market_proto_init() {
	if File_market_v1_market_proto != nil {
		return
	}
	file_market_v1_market_proto_msgTypes[4].OneofWrappers = []any{
		(*MarketEvent_Trade)(nil),
		(*MarketEvent_OrderBookUpdate)(nil),
		(*MarketEvent_Ticker)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_v1_market_proto_rawDesc), len(file_market_v1_market_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_v1_market_proto_goTypes,
		DependencyIndexes: file_market_v1_market_proto_depIdxs,
		EnumInfos:         file_market_v1_market_proto_enumTypes,
		MessageInfos:      file_market_v1_market_proto_msgTypes,
	}.Build()
	File_market_v1_market_proto = out.File
	file_market_v1_market_proto_goTypes = nil
	file_market_v1_market_proto_depIdxs = nil
}
